site_name: 'MuC Makerspace 2017'
#repo_url: 'https://github.com/FabLabSiegen/fab101-2017-muc-workshop'
#repo_name: 'fablabsiegen:muc-ms'
site_favicon: 'images/favicon-32x32.png'

pages:
    - MuC Makerspace: 'index.md'
    - Program : 'program.md'
    - Location : 'location.md'    
    - Organizers: 'organizers.md'
    - Imprint: 'imprint.md'


markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - footnotes

theme_dir: 'theme/material'
#theme: 'material'

extra_css:
    - css/footer.css
    - css/extra.css
    
    
extra:
  logo: 'images/logo.png'
  palette:
    primary: 'green'
    accent: 'deep orange'
  font:
    text: 'Open Sans'
    code: 'Inconsolata'
#  social:
#    - type: 'twitter'
#      link: 'https://twitter.com/cscwsiegen'
#    - type: 'facebook'
#      link: 'http://facebook.com/fablabsiegen'
